// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/demo-talent/internal/repository (interfaces: BudgetRepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/demo-talent/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockBudgetRepositoryInterface is a mock of BudgetRepositoryInterface interface.
type MockBudgetRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetRepositoryInterfaceMockRecorder
}

// MockBudgetRepositoryInterfaceMockRecorder is the mock recorder for MockBudgetRepositoryInterface.
type MockBudgetRepositoryInterfaceMockRecorder struct {
	mock *MockBudgetRepositoryInterface
}

// NewMockBudgetRepositoryInterface creates a new mock instance.
func NewMockBudgetRepositoryInterface(ctrl *gomock.Controller) *MockBudgetRepositoryInterface {
	mock := &MockBudgetRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBudgetRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetRepositoryInterface) EXPECT() *MockBudgetRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBudgetRepositoryInterface) Create(arg0 context.Context, arg1 *entities.Budget) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockBudgetRepositoryInterface) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockBudgetRepositoryInterface) GetByID(arg0 context.Context, arg1 string) (*entities.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entities.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).GetByID), arg0, arg1)
}

// List mocks base method.
func (m *MockBudgetRepositoryInterface) List(arg0 context.Context, arg1, arg2 int) ([]entities.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entities.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).List), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockBudgetRepositoryInterface) Update(arg0 context.Context, arg1 *entities.Budget) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).Update), arg0, arg1)
}
