// Code generated by MockGen. DO NOT EDIT.
// Source: budgets.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/demo-talent/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockBudgetRepositoryInterface is a mock of BudgetRepositoryInterface interface.
type MockBudgetRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetRepositoryInterfaceMockRecorder
}

// MockBudgetRepositoryInterfaceMockRecorder is the mock recorder for MockBudgetRepositoryInterface.
type MockBudgetRepositoryInterfaceMockRecorder struct {
	mock *MockBudgetRepositoryInterface
}

// NewMockBudgetRepositoryInterface creates a new mock instance.
func NewMockBudgetRepositoryInterface(ctrl *gomock.Controller) *MockBudgetRepositoryInterface {
	mock := &MockBudgetRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBudgetRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetRepositoryInterface) EXPECT() *MockBudgetRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBudgetRepositoryInterface) Create(ctx context.Context, b *entities.Budget) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).Create), ctx, b)
}

// Delete mocks base method.
func (m *MockBudgetRepositoryInterface) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBudgetRepositoryInterface) GetByID(ctx context.Context, id string) (*entities.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockBudgetRepositoryInterface) Update(ctx context.Context, b *entities.Budget) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBudgetRepositoryInterfaceMockRecorder) Update(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBudgetRepositoryInterface)(nil).Update), ctx, b)
}
