name: Smoke Tests
on:
  workflow_dispatch:
jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Run smoke tests
      run: |
        go run integration/smoke_tests/main.go